providers:
  openrouter:
    api_key: ${OPENROUTER_API_KEY}
    base_url: https://openrouter.ai/api/v1
    models:
      default: openrouter/gemini-2.0-flash
      options:
        - openrouter/gemini-2.0-flash
        - openrouter/gpt-4-turbo

  gemini:
    api_key: ${GEMINI_API_KEY}
    models:
      default: gemini-2.0-flash
      options:
        - gemini-2.0-flash
        - gemini-1.5-pro

default_provider: gemini
