providers:
  openrouter:
    api_key: ${OPENROUTER_API_KEY}
    base_url: https://openrouter.ai/api/v1
    models:
      default: google/gemini-2.0-flash-thinking-exp:free
      options:
        - qwen/qwq-32b:free
        - deepseek/deepseek-r1-zero:free
        - deepseek/deepseek-r1:free
        - google/gemini-2.0-flash-thinking-exp:free

  gemini:
    api_key: ${GEMINI_API_KEY}
    models:
      default: gemma-3-27b-it
      options:
        - gemini-2.0-flash
        - gemini-2.0-flash-thinking-exp-01-21
        - learnlm-1.5-pro-experimental

default_provider: gemini
